app/controllers/compress_pdf_controller.py
from flask import Blueprint, render_template, request
from app.models.pdf_model import compress_pdf
import os

compress_pdf_bp = Blueprint('compress_pdf', __name__)


@compress_pdf_bp.route('/compress-pdf', methods=['GET', 'POST'])
def compress_pdf():
    if request.method == 'POST':
        file = request.files['file']
        file_path = os.path.join('app/static/uploads', file.filename)
        file.save(file_path)

        output_path = os.path.join('app/static/uploads', 'compressed.pdf')
        compress_pdf(file_path, output_path)
    return render_template('compress_pdf.html')

app/controllers/extract_text_controller.py
from flask import Blueprint, render_template, request
from app.models.pdf_model import extract_text_from_pdf
import os

extract_text_bp = Blueprint('extract_text', __name__)

@extract_text_bp.route('/extract-text', methods=['GET', 'POST'])
def extract_text():
    text = None
    if request.method == 'POST':
        file = request.files['file']
        file_path = os.path.join('app/static/uploads', file.filename)
        file.save(file_path)
        text = extract_text_from_pdf(file_path)
    return render_template('extract_text.html', text=text)

app/controllers/home_controller.py
from flask import Blueprint, render_template

home_bp = Blueprint('home', __name__)

@home_bp.route('/')
def home():
    return render_template('home.html')

app/controllers/image_to_pdf_controller.py
from flask import Blueprint, render_template, request
from app.models.pdf_model import images_to_pdf
import os

image_to_pdf_bp = Blueprint('image_to_pdf', __name__)


@image_to_pdf_bp.route('/image-to-pdf', methods=['GET', 'POST'])
def image_to_pdf():
    if request.method == 'POST':
        files = request.files.getlist('files')
        image_paths = []
        for file in files:
            file_path = os.path.join('app/static/uploads', file.filename)
            file.save(file_path)
            image_paths.append(file_path)

        output_path = os.path.join('app/static/uploads', 'output.pdf')
        images_to_pdf(image_paths, output_path)
    return render_template('image_to_pdf.html')

app/controllers/merge_pdf_controller.py
from PyPDF2 import PdfReader, PdfWriter
from PyPDF2.generic import NameObject, NumberObject
from flask import Blueprint, render_template, request, url_for, jsonify, send_file
import os, io

merge_pdf_bp = Blueprint('merge_pdf', __name__)

@merge_pdf_bp.route('/merge-pdf', methods=['GET', 'POST'])
def merge_pdf():
    if request.method == 'POST':
        files = request.files.getlist('files')
        rotations = request.form.getlist('rotations')  # Recebe a lista de rotações

        if len(files) != len(rotations):
            return jsonify({'success': False, 'message': 'Erro: Descompasso entre arquivos e rotações.'})

        output = io.BytesIO()
        writer = PdfWriter()

        # Aplicar rotação para cada PDF individualmente
        for i, file in enumerate(files):
            reader = PdfReader(file)
            rotation = int(rotations[i])  # Obtém a rotação do arquivo específico

            for page in reader.pages:
                # Aplica a rotação acumulada
                current_rotation = page.get("/Rotate") or 0  # Obtém a rotação existente
                new_rotation = (current_rotation + rotation) % 360  # Calcula rotação acumulativa
                page.rotate(new_rotation)  # Aplica a rotação corretamente
                writer.add_page(page)  # Adiciona ao arquivo final

        writer.write(output)
        output.seek(0)

        # Salva como arquivo temporário
        temp_path = os.path.join('app/static/uploads', 'temp_merged.pdf')
        with open(temp_path, 'wb') as f:
            f.write(output.getvalue())

        return jsonify({
            'success': True,
            'redirectUrl': url_for('merge_pdf.merged_download', _external=True),
        })


    return render_template('merge_pdf.html')

@merge_pdf_bp.route('/merged-download')
def merged_download():
    file_path = os.path.join('app/static/uploads', 'temp_merged.pdf')
    if not os.path.exists(file_path):
        return render_template("download.html", success=False, message="Nenhum arquivo disponível para download.")

    download_url = url_for('static', filename='uploads/temp_merged.pdf', _external=True)
    return render_template("download.html", success=True, download_url=download_url,
                           file_title="Os PDFs foram combinados!", file_type='o PDF combinado')

@merge_pdf_bp.route('/delete-file', methods=['POST'])
def delete_file():
    filename = request.json.get('filename')

    if not filename:
        return jsonify({'success': False, 'message': 'Arquivo não especificado!'})

    file_path = os.path.join('app/static/uploads', filename)

    if os.path.exists(file_path):
        os.remove(file_path)
        return jsonify({'success': True, 'message': 'Arquivo excluído com sucesso!'})
    else:
        return jsonify({'success': False, 'message': 'Arquivo não encontrado!'})

@merge_pdf_bp.route('/rotate_pdf', methods=['POST'])
def rotate_pdf():
    """Rota responsável por processar a rotação do PDF no servidor."""
    from PyPDF2 import PdfReader, PdfWriter

    try:
        file_name = request.form.get('file_name')  # Nome único do arquivo
        rotation = int(request.form.get('rotation'))  # Ângulo de rotação

        # Identifica o arquivo no diretório (ajuste conforme a lógica do seu sistema de arquivos)
        input_path = f"./uploads/{file_name}"
        output_path = f"./uploads/rotated_{file_name}"

        # Rotacionar PDF
        reader = PdfReader(input_path)
        writer = PdfWriter()

        for page in reader.pages:
            page.rotate(rotation)
            writer.add_page(page)

        # Salva o resultado como um novo arquivo rotacionado
        with open(output_path, "wb") as output_file:
            writer.write(output_file)

        # Retorna sucesso ao frontend
        return jsonify({"status": "success", "file_name": f"rotated_{file_name}"})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500

app/controllers/pdf_to_excel_controller.py
from flask import render_template, Blueprint

pdf_to_excel_bp = Blueprint('pdf_to_excel', __name__)

@pdf_to_excel_bp.route('/pdf-to-excel', methods=['GET'])
def pdf_to_excel():
    return render_template('pdf_to_excel.html')

app/controllers/pdf_to_image_controller.py
from flask import Blueprint, render_template, request
from app.models.pdf_model import pdf_to_images
import os

pdf_to_image_bp = Blueprint('pdf_to_image', __name__)

@pdf_to_image_bp.route('/pdf-to-image', methods=['GET', 'POST'])
def pdf_to_image():
    images = None
    if request.method == 'POST':
        file = request.files['file']
        file_path = os.path.join('app/static/uploads', file.filename)
        file.save(file_path)
        output_folder = 'app/static/uploads'
        pdf_to_images(file_path, output_folder)
        images = [f for f in os.listdir(output_folder) if f.endswith('.png')]
    return render_template('pdf_to_image.html', images=images)

app/controllers/pdf_to_word_controller.py
from flask import Blueprint, request, jsonify, send_file, render_template, url_for, redirect
from pdf2docx import Converter
from PyPDF2 import PdfReader, PdfWriter
import os
import io
import tempfile

pdf_to_word_bp = Blueprint('pdf_to_word', __name__)

@pdf_to_word_bp.route('/pdf-to-word', methods=['GET'])
def pdf_to_word():
    return render_template('pdf_to_word.html')


@pdf_to_word_bp.route('/upload-pdf-to-word', methods=['POST'])
def upload_pdf_to_word():
    if 'file' not in request.files:
        return jsonify({'success': False, 'message': 'Nenhum arquivo enviado.'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'success': False, 'message': 'Nenhum arquivo selecionado.'}), 400

    try:
        # Ler o número de páginas do PDF
        pdf_reader = PdfReader(file)
        num_pages = len(pdf_reader.pages)

        return jsonify({'success': True, 'fileName': file.filename, 'numPages': num_pages})
    except Exception as e:
        return jsonify({'success': False, 'message': f'Erro ao processar o PDF: {str(e)}'}), 500

@pdf_to_word_bp.route('/convert-pdf-to-word', methods=['POST'])
def convert_pdf_to_word():
    if 'file' not in request.files:
        return jsonify({'success': False, 'message': 'Nenhum arquivo enviado.'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'success': False, 'message': 'Nenhum arquivo selecionado.'}), 400

    try:
        # Ler o arquivo PDF em memória
        pdf_stream = io.BytesIO(file.read())
        pdf_reader = PdfReader(pdf_stream)

        # Corrigir a rotação das páginas (se necessário)
        pdf_writer = PdfWriter()
        for page in pdf_reader.pages:
            rotation = page.get("/Rotate", 0)
            if rotation != 0:
                page.rotate(-rotation)  # Corrigir rotação
            pdf_writer.add_page(page)

        # Salvar o PDF corrigido em um arquivo temporário em memória
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_pdf:
            pdf_writer.write(temp_pdf)
            temp_pdf_path = temp_pdf.name

        # Converter PDF corrigido para Word em memória
        word_stream = io.BytesIO()
        cv = Converter(temp_pdf_path)
        cv.convert(word_stream)
        cv.close()

        word_stream.seek(0)

        # Excluir o arquivo temporário após a conversão
        import os
        os.remove(temp_pdf_path)

        # Retornar o arquivo Word para o usuário
        return send_file(
            word_stream,
            mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            as_attachment=True,
            download_name=f"{file.filename.rsplit('.', 1)[0]}.docx"
        )
    except Exception as e:
        # Excluir o arquivo temporário em caso de erro
        if 'temp_pdf_path' in locals() and os.path.exists(temp_pdf_path):
            os.remove(temp_pdf_path)
        return jsonify({'success': False, 'message': f'Erro ao converter o PDF: {str(e)}'}), 500

@pdf_to_word_bp.route('/download-hub', methods=['GET'])
def download_hub():
    # Renderiza a página de sucesso após o download
    return render_template('download.html')

app/controllers/split_pdf_controller.py
from flask import Blueprint, render_template, request, jsonify, send_file, url_for
from PyPDF2 import PdfReader, PdfWriter
import os
import io
import zipfile

split_pdf_bp = Blueprint('split_pdf', __name__, template_folder='../templates')

UPLOAD_FOLDER = "app/static/uploads"
OUTPUT_FOLDER = "app/static/output"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(OUTPUT_FOLDER, exist_ok=True)


@split_pdf_bp.route('/split-pdf', methods=['GET'])
def split_pdf():
    return render_template('split_pdf.html')


@split_pdf_bp.route('/upload-pdf', methods=['POST'])
def upload_pdf():
    if 'file' not in request.files:
        return jsonify({'success': False, 'message': 'Nenhum arquivo enviado.'}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({'success': False, 'message': 'Nenhum arquivo selecionado.'}), 400

    file_path = os.path.join(UPLOAD_FOLDER, file.filename)
    file.save(file_path)

    reader = PdfReader(file_path)
    num_pages = len(reader.pages)

    return jsonify({'success': True, 'fileName': file.filename, 'numPages': num_pages})


@split_pdf_bp.route('/process-split', methods=['POST'])
def process_split():
    file_name = request.form.get('fileName')
    split_option = request.form.get('splitOption')
    selected_pages = request.form.get('selectedPages', '')

    file_path = os.path.join(UPLOAD_FOLDER, file_name)
    if not os.path.exists(file_path):
        return jsonify({'success': False, 'message': 'Arquivo não encontrado.'}), 400

    try:
        reader = PdfReader(file_path)
        base_name = os.path.splitext(file_name)[0]

        zip_file_path = os.path.join(OUTPUT_FOLDER, f"{base_name}_dividido.zip")

        with zipfile.ZipFile(zip_file_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
            if split_option == 'all':
                for i, page in enumerate(reader.pages):
                    writer = PdfWriter()
                    writer.add_page(page)

                    pdf_buffer = io.BytesIO()
                    writer.write(pdf_buffer)
                    pdf_buffer.seek(0)

                    page_filename = f"{base_name}_pagina_{i + 1}.pdf"

                    zip_file.writestr(page_filename, pdf_buffer.getvalue())
            else:
                selected_pages = [int(p) - 1 for p in selected_pages.split(',') if p.isdigit()]

                for i, page_index in enumerate(selected_pages):
                    if 0 <= page_index < len(reader.pages):
                        writer = PdfWriter()
                        writer.add_page(reader.pages[page_index])

                        pdf_buffer = io.BytesIO()
                        writer.write(pdf_buffer)
                        pdf_buffer.seek(0)

                        page_filename = f"{base_name}_pagina_{page_index + 1}.pdf"

                        zip_file.writestr(page_filename, pdf_buffer.getvalue())

        download_url = url_for("static", filename=f"output/{base_name}_dividido.zip", _external=True)
        return jsonify({'success': True, 'redirect_url': url_for('split_pdf.download', download_url=download_url)})

    except Exception as e:
        print(f"Erro ao processar PDF: {e}")
        return jsonify({'success': False, 'message': 'Erro ao processar o PDF: ' + str(e)}), 500


@split_pdf_bp.route('/download', methods=['GET'])
def download():
    download_url = request.args.get('download_url', None)

    if not download_url:
        return render_template("download.html", success=False, message="Nenhum arquivo disponível para download.")

    return render_template("download.html", success=True, download_url=download_url, file_title="O PDF foi dividido!",file_type="PDF dividido")

app/controllers/watermark_controller.py
from flask import Blueprint, render_template, request
from app.models.pdf_model import add_watermark
import os

watermark_bp = Blueprint('watermark', __name__)


@watermark_bp.route('/watermark', methods=['GET', 'POST'])
def watermark():
    if request.method == 'POST':
        pdf = request.files['pdf']
        watermark = request.files['watermark']
        pdf_path = os.path.join('app/static/uploads', pdf.filename)
        watermark_path = os.path.join('app/static/uploads', watermark.filename)
        pdf.save(pdf_path)
        watermark.save(watermark_path)

        output_path = os.path.join('app/static/uploads', 'watermarked.pdf')
        add_watermark(pdf_path, watermark_path, output_path)
    return render_template('watermark.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Hub</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <!--<link rel="icon" href="{{ url_for('static', filename='images/Untitled.png') }}" type="image/x-icon">
            todo adicionar icone-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.0/Sortable.min.js"></script>

</head>
<body class="theme-light">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('home.home') }}">PDF Hub</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('merge_pdf.merge_pdf') }}">Juntar PDF</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('split_pdf.split_pdf') }}">Dividir PDF</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Converter PDF
                </a>
                <div class="dropdown-menu p-3 dropdown-custom" aria-labelledby="navbarDropdown">
                    <div class="d-flex">
                        <!-- Primeira Coluna -->
                        <div class="pr-3">
                            <h6 class="dropdown-header">Converter em PDF</h6>
                            <a class="dropdown-item" href="#">JPG para PDF</a>
                            <a class="dropdown-item" href="#">WORD para PDF</a>
                            <a class="dropdown-item" href="#">EXCEL para PDF</a>
                        </div>
                        <!-- Segunda Coluna -->
                        <div>
                            <h6 class="dropdown-header">Converter de PDF</h6>
                            <a class="dropdown-item" href="#">PDF para JPG</a>
                            <a class="dropdown-item" href="#">PDF para WORD</a>
                            <a class="dropdown-item" href="#">PDF para EXCEL</a>
                        </div>
                    </div>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('pdf_to_image.pdf_to_image') }}">PDF para Imagem</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('image_to_pdf.image_to_pdf') }}">Imagem para PDF</a>
            </li>
        </ul>
        <div class="custom-control custom-switch">
            <input type="checkbox" class="custom-control-input" id="themeSwitch">
            <label class="custom-control-label" for="themeSwitch">
                <span id="themeIcon">☀️</span> <!-- Ícone padrão (tema claro) -->
            </label>
        </div>
    </div>
</nav>
<div class="container mt-4">
    {% block content %}{% endblock %}
</div>
<script>document.body.classList.add('js-enabled');</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>

app/templates/compress_pdf.html
{% extends "base.html" %}

{% block content %}
<h2>Reduzir Tamanho do PDF</h2>
<p>Faça upload de um PDF para reduzir o tamanho.</p>

<form action="{{ url_for('compress_pdf.compress_pdf') }}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="file" accept="application/pdf" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary">Reduzir Tamanho</button>
</form>
{% endblock %}

app/templates/download.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center py-5">
    <h1 class="mb-3">Download Realizado com Sucesso!</h1>
    <p>O arquivo foi baixado e está pronto para uso!</p>
    <a href="/" class="btn btn-dark mt-4">Voltar para a página inicial</a>
</div>
{% endblock %}

app/templates/extract_text.html
{% extends "base.html" %}

{% block content %}
<h2>Extrair Texto de PDF</h2>
<p>Faça upload de um PDF para extrair o texto.</p>

<form action="{{ url_for('extract_text.extract_text') }}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="file" accept="application/pdf" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary">Extrair Texto</button>
</form>

{% if text %}
<div class="mt-4">
    <h3>Texto Extraído:</h3>
    <pre class="text-light">{{ text }}</pre>
</div>
{% endif %}
{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container" id="home_container">
    <h1 class="text-center my-4">Hub de Ferramentas PDF</h1>
    <br>
    <div class="row">
        <!-- Juntar PDF -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('merge_pdf.merge_pdf') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fa-solid fa-down-left-and-up-right-to-center fa-3x mb-3"></i> <!-- Ícone -->
                    <h5 class="card-title">Juntar PDF</h5> <!-- Título -->
                    <p class="card-text">Combine vários PDF em um único arquivo.</p> <!-- Subtítulo -->
                </div>
            </a>
        </div>

        <!-- Dividir PDF -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('split_pdf.split_pdf') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fa-solid fa-up-right-and-down-left-from-center fa-3x mb-3"></i><!-- Ícone -->
                    <h5 class="card-title">Dividir PDF</h5> <!-- Título -->
                    <p class="card-text">Divida o PDF em vários arquivos únicos.</p> <!-- Subtítulo -->
                </div>
            </a>
        </div>

        <!-- PDF para Word -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('pdf_to_word.pdf_to_word') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fa-solid fa-file-word fa-3x mb-3"></i>
                    <h5 class="card-title">PDF para Word</h5>
                    <p class="card-text">Transforme seus documentos PDF para Word DOCX.</p>
                </div>
            </a>
        </div>

        <!-- PDF para Excel -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('pdf_to_excel.pdf_to_excel') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fa-solid fa-file-excel fa-3x mb-3"></i>
                    <h5 class="card-title">PDF para Excel</h5>
                    <p class="card-text">Retire os dados do seu PDF para uma planilha Excel.</p>
                </div>
            </a>
        </div>

        <!-- PDF para JPG -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="#" class="card text-center h-100">
                <div class="card-body">
                    <i class="fa-solid fa-file-image fa-3x mb-3"></i>
                    <h5 class="card-title">PDF para JPG</h5>
                    <p class="card-text">Transforme seu PDF em uma Imagem JPG.</p>
                </div>
            </a>
        </div>

        <!-- Assinar Digitalmente -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="#" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-file-signature fa-3x mb-3"></i>
                    <h5 class="card-title">Assinar Digitalmente</h5>
                    <p class="card-text">Adicione uma assinatura digital ao PDF.</p>
                </div>
            </a>
        </div>

        <!-- Extrair Texto -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('extract_text.extract_text') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-file-alt fa-3x mb-3"></i>
                    <h5 class="card-title">Extrair Texto</h5>
                    <p class="card-text">Extraia texto de um arquivo PDF.</p>
                </div>
            </a>
        </div>

        <!-- PDF para Imagem -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('pdf_to_image.pdf_to_image') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-image fa-3x mb-3"></i>
                    <h5 class="card-title">PDF para Imagem</h5>
                    <p class="card-text">Converta páginas de PDF em imagens.</p>
                </div>
            </a>
        </div>

        <!-- Imagem para PDF -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('image_to_pdf.image_to_pdf') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-file-pdf fa-3x mb-3"></i>
                    <h5 class="card-title">Imagem para PDF</h5>
                    <p class="card-text">Converta imagens em um arquivo PDF.</p>
                </div>
            </a>
        </div>

        <!-- Adicionar Watermark -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('watermark.watermark') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-tint fa-3x mb-3"></i>
                    <h5 class="card-title">Adicionar Watermark</h5>
                    <p class="card-text">Adicione um watermark ao seu PDF.</p>
                </div>
            </a>
        </div>

        <!-- Reduzir Tamanho do PDF -->
        <div class="col-md-2 col-sm-6 mb-4">
            <a href="{{ url_for('compress_pdf.compress_pdf') }}" class="card text-center h-100">
                <div class="card-body">
                    <i class="fas fa-compress fa-3x mb-3"></i>
                    <h5 class="card-title">Reduzir Tamanho</h5>
                    <p class="card-text">Reduza o tamanho do arquivo PDF.</p>
                </div>
            </a>
        </div>

    </div>
</div>
{% endblock %}

app/templates/image_to_pdf.html
{% extends "base.html" %}

{% block content %}
<h2>Imagem para PDF</h2>
<p>Faça upload de imagens para converter em PDF.</p>

<form action="{{ url_for('image_to_pdf.image_to_pdf') }}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <input type="file" name="files" multiple accept="image/*" class="form-control-file">
    </div>
    <button type="submit" class="btn btn-primary">Converter para PDF</button>
</form>
{% endblock %}

app/templates/merge_pdf.html
{% extends "base.html" %}

{% block content %}
<h2>Juntar PDF</h2>
<p>Adicione os PDF, arraste para reordenar e ajuste conforme necessário.</p>

<form id="mergeForm" data-url="{{ url_for('merge_pdf.merge_pdf') }}">
    <div class="form-group">
        <input type="file" id="fileInput" accept=".pdf" multiple style="display: none;">
        <button type="button" id="addFilesBtn" class="btn btn-dark mb-3">
            <i class="fas fa-plus"></i> Adicionar Arquivos
        </button>
        <button type="button" id="sortByNameBtn" class="btn btn-secondary mb-3">
            <i class="fas fa-sort-alpha-down"></i> Ordenar por Nome
        </button>
    </div>

    <!-- Área de Preview dos PDFs -->
    <div id="pdfPreview" class="d-flex flex-wrap mb-3">
        <!-- Os PDFs serão adicionados aqui dinamicamente -->
    </div>

    <button type="submit" class="btn btn-success">
        <i class="fas fa-file-pdf"></i> Juntar PDF
    </button>
</form>

<template id="pdfTemplate">
    <div class="pdf-item card m-2" style="width: 150px;">
        <div class="card-body text-center">
            <canvas class="pdf-preview mb-2" style="width: 100%; height: 150px;"></canvas>
            <p class="card-text pdf-name">Nome do Arquivo</p>
            <div class="btn">
                <button type="button" class="btn btn-danger btn-sm delete-pdf">
                    <i class="fas fa-trash"></i>
                </button>
                <button type="button" class="btn btn-warning btn-sm rotate-pdf">
                    <i class="fas fa-sync"></i>
                </button>
            </div>
        </div>
    </div>
</template>

<script>
    var rotatePdfUrl = "{{ url_for('merge_pdf.rotate_pdf') }}";
</script>

<script src="{{ url_for('static', filename='js/merge_pdf.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.11.338/pdf.min.js"></script>

{% endblock %}